//问答机器人
export const ACTION_CHART_ROBOT_PRE_FETCH = 'ACTION_CHART_ROBOT_PRE_FETCH';
export const ACTION_CHART_ROBOT_FETCH_OK = 'ACTION_CHART_ROBOT_FETCH_OK';
export const ACTION_CHART_ROBOT_FETCH_ERROR = 'ACTION_CHART_ROBOT_FETCH_ERROR';