//在线新闻
export const ACTION_ONLINE_NEWS_PRE_FETCH = 'ACTION_ONLINE_NEWS_PRE_FETCH';
export const ACTION_ONLINE_NEWS_FETCH_OK = 'ACTION_ONLINE_NEWS_FETCH_OK';
export const ACTION_ONLINE_NEWS_FETCH_ERROR = 'ACTION_ONLINE_NEWS_FETCH_ERROR';

//微信精选（分页加载）
export const ACTION_WEIXIN_NEWS_PRE_FETCH = 'ACTION_WEIXIN_NEWS_PRE_FETCH';
export const ACTION_WEIXIN_NEWS_FETCH_OK = 'ACTION_WEIXIN_NEWS_FETCH_OK';
export const ACTION_WEIXIN_NEWS_FETCH_ERROR = 'ACTION_WEIXIN_NEWS_FETCH_ERROR';

//Home页top banner
export const ACTION_HOME_BANNER_FETCHED = 'ACTION_HOME_BANNER_FETCHED';